# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: About me
    url: '#about'
    weight: 10
  - name: Awards
    url: '#posts' # todo update
    weight: 20
  - name: Projects
    url: '#project'
    weight: 30
  - name: Professional experience
    url: '#featured'
    weight: 40
  - name: Posts
    url: '#posts'
    weight: 50
  - name: studies
    url: '#contact'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
