name: Updater (WIP)

on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    if: github.repository_owner == 'HugoBlox'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run updater
        uses: HugoBlox/gh-action-updater@v1
        with:
          feed-url: https://hugoblox.com/rss.xml
          readme-section: news
          branch: main
